apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microlearning-wiki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bdridi/argocd-3-in-1.git
    targetRevision: HEAD
    path: demo/applications/microlearning/wiki
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: microlearning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true