apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bdridi/argocd-3-in-1.git
    targetRevision: HEAD
    path: demo/applications/nginx
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true